name: Build n8n Docker image with FFmpeg

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
            docker build --platform linux/${{ matrix.platform }} -t ${{ secrets.DOCKERHUB_USERNAME }}/n8n-ffmpeg:latest-${{ matrix.platform }} .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/n8n-ffmpeg:latest-${{ matrix.platform }}
  
  create-manifest:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push Docker Manifest
        run: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/n8n-ffmpeg
            MANIFEST_TAG=latest
            docker manifest create \
              $IMAGE_NAME:$MANIFEST_TAG \
              --amend $IMAGE_NAME:latest-amd64 \
              --amend $IMAGE_NAME:latest-arm64
            docker manifest push $IMAGE_NAME:$MANIFEST_TAG
